### ISSUE TITLE
Add recs for obsolete_pkg_deps

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#107]
In https://github.com/ropensci-review-tools/pkgcheck/pull/69/files for each obsolete dep there was the name of the alternative. Or maybe there could be a link to the related dev guide section https://devguide.ropensci.org/building.html#recommended-scaffolding

**Comment by mpadge** [comment]
Good idea, and great opportunity to develop a new `print` method. One thing I've been ignoring until now is the ordering of `print` methods, which this will be be a perfect opportunity to address. Thanks!

**Comment by mpadge** [comment]
@maelle This has now been addressed through functionality demonstrated at https://github.com/ropensci-review-tools/pkgcheck/issues/44#issuecomment-974008803, right? Happy to close?

**Comment by maelle** [comment]
Yes!
