### ISSUE TITLE
[BUG] in CI checks

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#109]
software-review#485 for https://github.com/oggioniale/ReLTER reports 2 CI badges, but actually there is no CI at all. Need to fix that!

**Comment by maelle** [comment]
ah interesting, it means the regex on github badges should be stricter?

Also note that this README has badges _in HTML comments_: should the code exclude those?

**Comment by mpadge** [comment]
Good catch with the HTML comments - fixing the main issue was a single line; removing those required a whole new function. Done now, and should all work. I'll re-deploy today to ensure re-checks catch lack of CI.
