### ISSUE TITLE
Fix snapshots of html outputs

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#111]
They include all sorts of `.js` src files that likely depend on machines, architecture, and other local idiosyncrasies. Have to remove any potentially machine-dependent stuff from html produced by `rmarkdown:::render` prior to snapshotting.

**Comment by mpadge** [comment]
@maelle FYI the closing commit above adds [this `clean-snapshots.R` script](https://github.com/ropensci-review-tools/pkgcheck/blob/main/tests/clean-snapshots.R) which is absolutely necessary for cleaning html snapshots rendered with `rmarkdown`.

**Comment by mpadge** [comment]
Hmmm ... snapshots are still not stable :question: :confused:

**Comment by maelle** [comment]
what differences do you see? is it Pandoc? :sob:

**Comment by mpadge** [comment]
Can't see any coz haven't yet found time to reproduce, and it is only on github checks that this is happening. I don't think it's pandoc, but also have no idea (yet) what it actually is. I'll report back when i find out more

**Comment by mpadge** [comment]
That green tick above says it all. Finally fixed this, and hope never to have to debug anything like that again.
