### ISSUE TITLE
Problem with rappdirs::user_cache_dir on Windows

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck#120]
I looked into why the windows CI keeps failing and one issue is this:
https://github.com/ropensci-review-tools/pkgcheck/blob/8fe4021c012eb5ae58e0ebffb045227b55635f31/R/zzz.R#L7
This should give: `C:\\Users\\<username>\\AppData\\Local\\Cache\\pgkcheck` but actually (tested on windows laptop) produces `C:\\Users\\<username>\\AppData\\Local/Cache/pgkcheck` which then causes an error when the cache is saved. (I think)

I saw you re-implemented some {fs} functionality, would you consider taking a dependency on fs to replace the base functions? (which is obviously a bit of work but prevents cross platform issues like this)

**Comment by mpadge** [comment]
Yep, for sure. The same kind of issues plagued `pkgstats` too, for which i also ended up importing ``fs`. It's used in the ["ctags" routines](https://github.com/ropensci-review-tools/pkgstats/blob/main/R/tag-data.R). Feel free to PR if you want - actually that'd be good because i don't have access to a windows machine to test.

**Comment by mpadge** [comment]
This can actually be addressed by broadly following the steps used to fix all the issues on macOS in #125 - it's all related to paths created internally via `file.path` or `fs::path` or whatever being different to the ones that are actually created. Good examples are now provided [in this workflow result](https://github.com/ropensci-review-tools/pkgcheck/runs/4924943952?check_suite_focus=true), like these:
```
actual vs expected
- "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\RtmpGOSfx0\\working_dir\\RtmpkXYCgX\\pkgcheckb10609353d7\\.github/pkgcheck.yaml"
+ "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\RtmpGOSfx0/working_dir\\RtmpkXYCgX/pkgcheckb10609353d7/.github/pkgcheck.yaml"
```
Solution:
1. Get rid of everything before `\Temp`; then
2. `fs::path_tidy()` the rest.

**Comment by assignUser** [comment]
Ah, this was the issue we had, with the path truncation to "RUNNER~", we fixed it with some fs thing... Path_real or so?

**Comment by mpadge** [comment]
Nice. That won't fix all of it, I fear, because there are still other more cryptic issues that originally led to me spawning off the windows checks to `extra-OS`, but this might all give good insight into how to resolve those issues too.

**Comment by assignUser** [comment]
yeah `fs::path_real`  Pretty sure it was this:
https://github.com/lorenzwalthert/touchstone/blob/d312b69a2239fd4f8f265f6074f96b9466b54fdd/R/utils.R#L242

**Comment by mpadge** [comment]
@assignUser Do you reckon this is still an issue? Or can we close and at least ignore for now?

**Comment by assignUser** [comment]
IIRC this was actually a broader issue with cache files on windows right? So nothing to do for now I guess 🤷
