### ISSUE TITLE
PAT for workflow dispatch to trigger pkgcheck-action build workflow

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck#123]
After testing the problem it turns out that we need to use a PAT with `repo` scope by an account that has access  to both repos even though they are in the same org.

I think the most secure and long term least maintenance intensive version would be a machine user that is part of the `ropensci-review-tools org. @mpadge maybe you already have something like that for the bot?

Otherwise a user would need to create a PAT with `repo` scope and add it to this repos secrets (which would give full access to all their public and private repos :fearful: )  

To illustrate how the result may look I have created a pair of repos:

This wf in A: https://github.com/assignUser/test-repo-a/runs/4885810223?check_suite_focus=true
Triggers this wf in B: https://github.com/assignUser/test-repo-b/runs/4885814274?check_suite_focus=true

**Comment by mpadge** [comment]
That's all really cool, but I'm not sure what problem this would be solving? Sorry for my confusion here ...

**Comment by assignUser** [comment]
This would keep the `pkgcheck-action` docker build up-to-date with this package. Without this the pkgcheck-action would need a pretty regular cron to stay on track and even then could be outdated if you push after the cron time.

**Comment by assignUser** [comment]
This is definitely the 100% solution and if you don't already have a machine user, I think a daily or weekly Cron to trigger the pkgcheck-action would also be adequate once {pkgcheck} is on CRAN... Should there be any important changes (e.g new tests) we can always trigger the build manually.

**Comment by mpadge** [comment]
I'm not sure how to solve this then, but I'm sure we'll find a way. [The `ropensci-review-bot`](https://github.com/ropensci-review-bot) works because it is a user/org. You can't create a user-bot w*within* an org. We could easily give the bot write access, , but i'm not sure how we'd pass its token to the workflows?

**Comment by mpadge** [comment]
I've put a token here and in `pkgcheck-action` called "RRT_TOKEN" that has write access to both, but the workflows rely on the default (repo-specific) "GITHUB_TOKEN", and i'm not sure how to override that? Do you know?

**Comment by assignUser** [comment]
Oh cool! Yeah `github-script` has `github-token:` as an input. One sec!

**Comment by mpadge** [comment]
yeah, just realised my dumb question too:
```
        with:
          github-token: ${{ secrets.RRT_TOKEN }}
```

**Comment by assignUser** [comment]
just 35minutes to wait... https://github.com/ropensci-review-tools/pkgcheck/runs/4886882025?check_suite_focus=true

**Comment by assignUser** [comment]
Works! 🎉 https://github.com/ropensci-review-tools/pkgcheck-action/actions/runs/1725172265

**Comment by mpadge** [comment]
NOTE: The token currently has a 30-day expiry. The commit above is yet another workflow to add a monthly reminder message to this thread to renew the token.

**Comment by mpadge** [comment]
@mpadge It's time to renew your 'RRT_TOKEN'
- grant both repo and workflow access
- copy token to \`pkgcheck-action\` repo secrets

**Comment by mpadge** [comment]
Re-opening to update the workflow message above to indicate explicityly that the token must first bn generated as a valid personal token, then copied over to both repos.

**Comment by mpadge** [comment]
Re-opening to update CRON job to ease off the update frequency here, by changing from monthly to bi-monthly. Tokens can be then created with 90-day validity.
