### ISSUE TITLE
visjs artefacts can not be directly viewed

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#127]
@assignUser This is not really a problem, but we need to document that the links to the artefacts produced in the auto-generated issue **do not work**, and instead re-direct people to the `.zip` artefacts which the `actions/upload-artefact` step produces. They can be clicked and opened anyway, so it just requires something like 2 clicks instead of one to see the artefact. This issue might also be better moved to `pkgcheck` itself, where I could update the path to, and description of, the `visjs` network if the checks are generated on github runners. Any thoughts from you side before I do that?

**Comment by mpadge** [comment]
Argh, i should not have commit that to `main` :frowning_face: - it changes the snapshots, but those can only be re-generated on the main workflow. I'll now have to split into two tests with corresponding snapshots, one to run locally and one on GitHub.

**Comment by mpadge** [comment]
Nope, that still doesn't fix, because the paths include the randomly-generated job ID. Have to solve it by doing an arbitrary re-substitution in [the `clean-snapshot` file](https://github.com/ropensci-review-tools/pkgcheck/blob/main/tests/clean-snapshots.R).

**Comment by assignUser** [comment]
yeah snapshot of messages with dynamic parts are a pain... (e.g. filenames in sucess/error msgs) It is suprising that there is no way to mark certain bits of a snapshot as dynamic and have testthat ignore those parts.

**Comment by mpadge** [comment]
Yes, surely files like [the `clean-snapshot.R` file](https://github.com/ropensci-review-tools/pkgcheck/blob/main/tests/clean-snapshots.R) are gong to be needed everywhere? It's even more annoying when generating HTML files, because they are clearly generated on GitHub by using some system that is reliant on headless chrome to generate the HTML, so anybody using a system which rejects all google-based components (like me) can't ever reproduce GitHub-generated HTML, and no needs some form of "clean-snapshots" ... But still, the whole system is so advantageous that i'm happy to keep on beta-testing for now ...

**Comment by mpadge** [comment]
Finally fixed!!! :100: :rocket: :guitar:
