### ISSUE TITLE
Link to workflow in visjs description broken

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck#133]
The link is not generated correctly, see https://github.com/assignUser/octolog/issues/4

**Comment by mpadge** [comment]
Ha, interesting - that error arose because the local path of workflow repos is a generic `github.com/github/workspace`. I was presuming it inherited the repo name, but it does not. That commit should fix - please re-open if not.

**Comment by mpadge** [comment]
Nope, still didn't fix, because it needs an error catch in case pkg has no URL

**Comment by mpadge** [comment]
Still not fixed ...

**Comment by assignUser** [comment]
I would suggest using the envvars containing repo name etc: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

**Comment by mpadge** [comment]
oh yeah, thanks! I've done that, but this now requires some tricky modification of the whole `tests/clean-snapshots` scripts. Then it should be there.

**Comment by mpadge** [comment]
Thanks Jacob, all looks better now. Now we just have to wait for the docker rebuilt and we'll be able to confirm with our local actions. Sorry about so many fails here - i should never have committed this to the main branch!

**Comment by assignUser** [comment]
No worries :D
