### ISSUE TITLE
covr underreporting coverage with expect_snapshot

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck#134]
As I discovered in https://github.com/ropensci/software-review/issues/502#issuecomment-1032925589 there is an issue with {covr} (severely) under reporting coverage when `expect_snapshot` is used. There is a [{covr} issue](https://github.com/r-lib/covr/issues/482) about this but there has not been a lot of movement. 

Not sure what to do about it in pkgcheck though, maybe detect usage of `expect_snapshot` and add a note to the editor/reviewers?

**Comment by assignUser** [comment]
>  Package coverage is 94.6%.

It looks like the review bot has the correct result for some reason. @mpadge any idea on the difference? As the action uses the same docker container and does fail. I tried the current cov dev version but that also did not resolve this issue.

**Comment by assignUser** [comment]
Found the difference, in the ro api's Dockerfile `NOT_CRAN` is set. I just tested this locally and it causes covr to report correctly. I will add this to the pkgcheck-action Dockerfile but we might want to set this within pkgcheck (-> {withr}?) to make the results consistent locally.

**Comment by mpadge** [comment]
Thanks @assignUser - the above commit adds same lines as in `pkgcheck-action`, but comments out the first:
https://github.com/ropensci-review-tools/pkgcheck/blob/106c69bff2404601e692fe5d41b77a4b7f3e0414/Dockerfile#L159-L160

Remote updates are important for the action, and for ropensci-review-tools/roreviewapi, but this Dockerfile is intended to rely on stable releases only. Just so you know.
