### ISSUE TITLE
Add :eyes: checks as well as just :heavy_check_mark: and :heavy_multiplication_x: 

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#144]
Checks like the latest `unique_fn_names` #142 might be better changed from currently unavoiable failure:

- :heavy_multiplication_x: Function names are duplicated in other packages

to a new section at the bottom of the summary:

---

### Checks subject to editorial discretion

- :question: Function names are duplicated in other packages

---

Thoughts @maelle:question:

**Comment by maelle** [comment]
I agree on the idea but am not sure the emoji is optimal. Maybe a warning sign or some sort of notebook?

**Comment by assignUser** [comment]
I was actually about to comment this on the closed issue!
⚠️ 🗒️ 📓 👀 👁️ 👁️‍🗨️ 

I think 👀 communicates the intent the best?

**Comment by maelle** [comment]
oh yeah, good idea!

**Comment by mpadge** [comment]
Whatever we decide, it also needs to be translated into corresponding HTML, which i do something like:
1. Text search on [this GitHub emoji reference page](https://emcorrales.com/cheatsheets/github-emojis#symbols) 
2. Locate same emoji on [this page](https://unicode.org/emoji/charts/full-emoji-list.html) to ensure it'll look the same / okay, and find the hex code.
3. Finally, search for same hex code on [this page](https://www.w3schools.com/charsets/ref_emoji.asp) to find the HTML code.

Doing that gives this: :eyes:  &#128064;, where the latter is `&#128064;`. Phew :sweat:

**Comment by assignUser** [comment]
Love it 👀

**Comment by mpadge** [comment]
Cool, thanks. It's already deployed too, so should appear anytime now ...
