### ISSUE TITLE
check renv.lock files

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#149]
- [ ] version of R should be latest
- [ ] All package versions should be latest
- [ ] Any fails on `renv::restore()` should trigger check failure

Fail if either of these conditions fail. @maelle Thoughts on this as an additional check?

**Comment by maelle** [comment]
Why would one use renv at all when developing a package :-)

**Comment by mpadge** [comment]
Or just prohibit usage of {renv} completely? Either fail a check or issue some kind of warning if it is used, or completely ignore it?

**Comment by maelle** [comment]
yes with maybe some docs in the dev guide around this/pointers.

- does one need minimal version for dependencies (I think it's mentioned somewhere in the dev guide)
- use of CI to test on different versions if needed

**Comment by mpadge** [comment]
The above commits add all of the intrastructure to execute (a [local version](https://github.com/ropensci-review-tools/pkgcheck/blob/a78c2c608bf9c72fae8fc88b95e73896a4e1559e/R/info-renv.R#L18-L53) of) [`renv::deactivate()`](https://rstudio.github.io/renv/reference/deactivate.html) on any packages which use `renv`. This uses a new `info-renv` file which adds binary `checks$info$uses_renv` to pass on to the check itself, `pkgchk_uses_renv`. All infrastructure for that check is there, but it is currently inactive. Activate by uncommenting the following line:

https://github.com/ropensci-review-tools/pkgcheck/blob/a78c2c608bf9c72fae8fc88b95e73896a4e1559e/R/pkgcheck-methods.R#L68

**Comment by mpadge** [comment]
Actually should modify this just  to ensure that renv is not activated. Using it is okay; it just shouldn't be [activated](https://github.com/rstudio/renv/blob/main/R/activate.R). Next commit will change the check to ensure either no local `.Rprofile` file exists, or if so, that it has `# source("renv/init.R")` - commented out, and not active. That should also be sufficient to switch the actual check on and close this issue. The only packages which fail will be those with renv actually activated, for which a failure seems fair enough.

**Comment by mpadge** [comment]
This test  is now live, and fails only when renv is both present and activated. It has a summary method only, and only on check fails.

**Comment by maelle** [comment]
Thank you!
