### ISSUE TITLE
Issue when trying to run pkgcheck

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci-review-tools/pkgcheck#152]
I hit this issue: 

```
pkgcheck::pkgcheck()
ctags: unrecognized option '--sort=no'
	Try 'ctags --help' for a complete list of options.
Error in normalizePath(path, mustWork = TRUE) : 
  path[1]="/tmp/RtmpnilKJT/file28754593ae16f.txt": No such file or directory
```

Reprex: clone robinlovelace/simodels and try the above command.

**Comment by maelle** [comment]
Thanks for the bug report!

FWIW I get

```
> pkgcheck::pkgcheck()

── simodels 0.0.4 ─────────────────────────────────────────────────────────

✔ Package name is available
✖ does not have a 'codemeta.json' file.
✖ does not have a 'contributing' file.
✔ uses 'roxygen2'.
✔ 'DESCRIPTION' has a URL field.
✔ 'DESCRIPTION' has a BugReports field.
✔ Package has at least one HTML vignette
✔ All functions have examples.
✔ Package has continuous integration checks.
✖ Package coverage failed
✖ R CMD check process failed with message: 'Build process failed'.

ℹ Current status:
✖ This package is not ready to be submitted.


── git ──

• HEAD: d7c5a99a
• Default branch: main
• Number of commits: 99
• First commit: 15-04-2022
• Number of authors: 4


── Package Structure ──

ℹ Package uses the following languages:
• R: 100%

ℹ Package has
• 2 authors.
• 3 vignettes.
• 4 internal data files.
• 5 imported packages.
• 3 exported functions (median 27 lines of code).
• 8 non-exported functions (median 14 lines of code).
• 7 parameters per function (median).

── Package statistics ──

                    measure   value percentile noteworthy
1                   files_R     5.0       34.7           
4           files_vignettes     4.0       95.3           
5               files_tests     0.0        0.0       TRUE
6                     loc_R   116.0       13.0           
7             loc_vignettes   582.0       81.6           
8             num_vignettes     3.0       94.2           
9           data_size_total 81076.0       82.2           
10         data_size_median 18456.0       82.8           
11                  n_fns_r    11.0       15.0           
12         n_fns_r_exported     3.0       12.9           
13     n_fns_r_not_exported     8.0       18.0           
14         n_fns_per_file_r     3.0       49.3           
15        num_params_per_fn     7.0       85.3           
16             loc_per_fn_r    21.0       62.0           
17         loc_per_fn_r_exp    27.0       58.8           
18     loc_per_fn_r_not_exp    14.0       46.2           
19         rel_whitespace_R     7.8        8.5           
20 rel_whitespace_vignettes    23.2       74.3           
21      doclines_per_fn_exp    48.0       60.6           
22  doclines_per_fn_not_exp     0.0        0.0       TRUE
23     fn_call_network_size     4.0       20.1           

ℹ Package network diagram is at [/home/maelle/.cache/pkgcheck/static/simodels_pkgstatsd7c5a99a.html].


── goodpractice ──

── GP simodels ────────────────────────────────────────────────────────────

It is good practice to

  ✖ use '<-' for assignment instead of '='. '<-' is the
    standard, and R users and developers are used it and it is
    easier to read your code for them if you use '<-'.

    R/si_model.R:46:14
    R/si_model.R:55:8
    R/si_model.R:56:6
    R/si_model.R:58:8
    R/si_model.R:61:8
    ... and 36 more lines

  ✖ avoid long code lines, it is bad for readability.
    Also, many people prefer editor windows that are about 80
    characters wide. Try make your lines shorter than 80
    characters

    R/si_model.R:6:1
    R/si_model.R:8:1
    R/si_model.R:11:1
    R/si_model.R:15:1
    R/si_model.R:39:1
    ... and 3 more lines

─────────────────────────────────────────────────────────────────────────── 
── Package Versions ──

  pkgstats: 0.0.4.75
  pkgcheck: 0.0.3.60
```

Although R CMD check actually passes in the RStudio build tab. So maybe another issue @mpadge 

@Robinlovelace in the meantime you could try using the GitHub Action? `pkgcheck::use_github_action_pkgcheck()` Although GitHub Actions can create other sorts of problems.

**Comment by mpadge** [comment]
Hiya Robin, i guess you're on a Linux system there? That suggests that ctags is not installed properly, whcih you can test locally by running [`pkgstats::ctags_test()`](https://docs.ropensci.org/pkgstats/reference/ctags_test.html). That will probably fail? If so, you should be able to then run `ctags_install(sudo = TRUE)` to intall it. Otherwise, the actual installation lines are given [in the GitHub  workflow file](https://github.com/ropensci-review-tools/pkgstats/blob/1a509b8fbf9dc573c94d6785e5c3fe13121faa5d/.github/workflows/check-standard.yaml#L58-L63). Just run them and you should be right.

**Comment by Robinlovelace** [comment]
Correct, in Linux. Worth adding installation instructions in the error message?

**Comment by mpadge** [comment]
Great point. I'll close with a commit which does that. Thanks!

**Comment by mpadge** [comment]
No wait, the appropriate error message is issued here:
https://github.com/ropensci-review-tools/pkgcheck/blob/5401c142c6aecf4b9cc29de77c55e0c3768e516e/R/pkgcheck-fn.R#L29-L38
... but only `if(!interactive())`. That means that message is skipped in reprex, among other environments. We can't just remove the `if(interactive())`, because that error condition has to be skipped in general on non-interactive environments. `reprex` just passes the calling environment through, so we could set a higher-level envvar in the package, such as `.onLoad` in an interactive environment. Then any non-interactive sub-processes which inherit the original environment would have that  variable. @Robinlovelace or @maelle Can either of you think of any smarter ways?

**Comment by maelle** [comment]
why does the error have to be skipped in non interactive environments?

**Comment by maelle** [comment]
then if just for reprexes you could
- use `rlang::is_interactive()` in pkgcheck code instead of the base R equivalent
- set the `rlang_interactive` option before running a reprex (but who would think of doing that :sweat_smile: )

**Comment by mpadge** [comment]
> why does the error have to be skipped in non interactive environments?

I actually don't remember why i put that there, and am not even sure that what i said above is correct. I know at the time i though it was something needed for bot functionality somehow, but can't find anything there that would actually need this. I'll close this with next commit by simply removing that line.

**Comment by mpadge** [comment]
No wait, i know what it was. Leaving that there makes the package impossible to test on CRAN windows machines! The `ctags_test()` function takes way too long, and has to be run at the very start. I need to think of a clever way of avoiding that on CRAN machines while leaving it intact everywhere else, including `!interactive()`.

**Comment by assignUser** [comment]
@mpadge that's why `NOT_CRAN` exists, not sure if that solution works for this though...

**Comment by Robinlovelace** [comment]
Can the error message happen earlier, e.g. when someone tries to install it on a computer that does not have the appropriate system deps? Appreciate the quickfire comms on this, many thanks!

**Comment by assignUser** [comment]
> doesn't actually "exist" in any reliable way,

Bad UX -> having to set `NOT_CRAN` every time to get the package to work :D

**Comment by kellijohnson-NOAA** [comment]
I have a suggestion for this code that was added to fix this issue but I am wondering if I should reopen this issue or open a new issue?

**Comment by mpadge** [comment]
@kellijohnson-NOAA Great that you're getting involved here. I'll leave it to your judgement. Directly related = re-open and continue. Tangentially related or brings up additional issues = new issue. Looking forward to your insights :+1:
