### ISSUE TITLE
Add vignette listing all checks currently implemented

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#158]
There is currently no clear reference for implemented checks other than the output of [`list_checks()`](https://docs.ropensci.org/pkgcheck/reference/list_pkgchecks.html). That only names them, but gives no description. A vignette could easily be created by using `roxygen2` to parse all of the blocks, and outputting those from check functions in some structured format.

**Comment by mpadge** [comment]
@maelle Thank you! The above commit was directly inspired by your awesome [newsletter scripts](https://github.com/ropensci/roweb3/blob/main/content/blog/2022-07-22-ropensci-news-digest-july-2022/index.Rmd) and my ever-growing appreciation of the magic that is `roxygen2`. The vignette just parses the roxgygen blocks for the **un-exported** `pkgck_<...>` functions and dumps the results as a vignette describing the checks. Nice!!

**Comment by mpadge** [comment]
## TODO

- [ ] Tidy documentation blocks for all check functions

I wasn't worrying about them because they're non-exported functions, but rendering all blocks in a vignette makes immediately apparent the need to improve docs for all check functions.

**Comment by maelle** [comment]
very cool! you wrote it'd be easy so I was especially curious :smile_cat:

**Comment by mpadge** [comment]
Only real difference is that i'm nowhere near as purrrrrrryyy :cat: :joy_cat: as you :smile_cat:
