### ISSUE TITLE
problems with `pkgcheck::pkgcheck()`

### ISSUE THREAD

**Issue by s3alfisc** [ropensci-review-tools/pkgcheck#160]
Hi all, I have some problems with running `pkgcheck()` on my [fwildclusterboot](https://github.com/s3alfisc/fwildclusterboot) package and windows machine. 

If I run it on my development version (inside of an R-studio project), I receive the following error 

```
pkgcheck::pkgcheck()
# Error in normalizePath(path.expand(path), winslash, mustWork) : 
# path[1]="C:\Users\alexa\Dropbox\fwildclusterboot/NA": The system cannot find the file specified
```

If I do the same on a clone of the github repo, I receive another error: 

```
pkgcheck::pkgcheck("C:/Users/alexa/Documents/R/win-library/4.1/fwildclusterboot/")
# Error in gsub(paste0(path, .Platform$file.sep), "", ftypes$file) : 
# invalid regular expression 'C:\Users\alexa\Documents\R\win-library\4.1\fwildclusterboot/', reason 'Invalid back reference'
```

As a last observation: I can run `pkgcheck::pkgcheck()` line-by-line without creating the error above. 

I further believe that the errors are related to fwildclusterboot - I can run `pkgcheck()` on the dev version of the [summclust](https://github.com/s3alfisc/summclust) package on my machine without any problems. 

Best, Alex

**Comment by assignUser** [comment]
It looks like the[ GHA](https://github.com/s3alfisc/fwildclusterboot/runs/8009932893?check_suite_focus=true) runs fine on your package, so I don't think this is an issue with your package. 

The second attempt does likely not work because you run it on what looks like the installed package. The first attempt should work assuming you are in the root of your package git repo. If it is just the files without the git repo (`.git`), which the Dropbox path makes me think, it won't work. `pkgcheck` only works on the package in git repo (which would explain why you have the failure only locally but the GHA works fine).

Please try to run `pkgcheck` within the proper git repo of your package, that should work!

**Comment by assignUser** [comment]
I just successfully ran pkgcheck on win 10 on a fresh clone of fwildclusterboot@master:
![image](https://user-images.githubusercontent.com/16141871/187032015-7c928087-27c0-4fa9-9693-68a0bc634f37.png)

**Comment by mpadge** [comment]
Thanks @assignUser for the help here! @s3alfisc can you confirm that problem persists with a fresh repo clone on your local machine? I presume not, since the `pkgcheck-action` workflows all seem to be working fine. Please let us know.

**Comment by s3alfisc** [comment]
Also from my side, thanks @assignUser! I have tried to run `pkgcheck` in a fresh repo clone yesterday, but did not get it to run. I probably should have replied yesterday already but thought I should put a little bit more effort into debugging myself before reporting back that I 'failed', as it might simply be that I have not tried enough. So sorry for not responding yesterday! I'll try to get back to this within this week.

**Comment by s3alfisc** [comment]
Hi all, sorry for taking so long to get back to this - when I run `pkgcheck()` on a fresh clone, I unfortunately still don't manage to get it to run. Given the fact that @assignUser did succeed in doing so and the `pkgcheck` action is running with `fwildclusterboot`, I assume that the error might in the end lie in my personal setup, and I would suggest to close this thread?

**Comment by mpadge** [comment]
Thanks @s3alfisc - hope you manage to figure it out :smile:

**Comment by s3alfisc** [comment]
Just to get back to this: I just installed to current version of `pkgcheck()` on a fresh R installation (4.2.0), and finally `pkgcheck::pkgcheck()` is running on my local machine! 🚀 🥳
