### ISSUE TITLE
avoid checking internal functions

### ISSUE THREAD

**Issue by dusadrian** [ropensci-review-tools/pkgcheck#161]
Hi, I've just ran `pkgcheck()` on my package [declared](https://github.com/dusadrian/declared), and one of the problems is that internal functions are reported as not having "documented return values".

The trouble is, internal functions are by definition undocumented. If they were documented, they would not be internal.

In some situations, documenting is not even possible, for instance `[` is a primitive base function for which I've added an S3 method `[.declared`. This is an internal function, that is registered in the Namespace, but it has no documentation of its own.
The questions is, how could such functions have a "documented return value"?

Alternatively, is there a method to instruct `pkgcheck()` to ignore internal functions?

**Comment by mpadge** [comment]
That check indeed had a couple of bug, potentially including the behaviour you mention, but has since been updated. I ran checks locally on your package, and all was clear. Please re-install and ensure you've got version >= 0.1.0.21. Please close issue if that resolves your problem. Thanks

**Comment by mpadge** [comment]
(But by the way, internal functions can be documented, and doing so is recommended by rOpenSci, as it helps other understand your code. They should then just be appended with a ˋ@noRdˋ tag instead of ˋ@exportˋ - see [Dev Guide](https://devguide.ropensci.org) for more details.)

**Comment by dusadrian** [comment]
Excellent, thank you very much @mpadge. 
The suggestion about `@nord` is very useful, I did not know about it (but will surely use it from now on).
