### ISSUE TITLE
pkgcheck time out

### ISSUE THREAD

**Issue by trangdata** [ropensci-review-tools/pkgcheck#166]
Hey there, 👋🏽 

I have pkgcheck as an Action for the package openalexR. It has been working well, but for some reason, yesterday, the action timed out even when I reran. Would love to get any insight! 🙏🏽 

https://github.com/massimoaria/openalexR/actions/runs/4138134587/jobs/7157493220

**Comment by assignUser** [comment]
Hello!

Could be that the github runner lost connection and didn't transmit an error code or something. Hard to say but probably unrelated to the action as the previous runs worked as intended (it is intentional that it fails if there where any issues found). If it happens again please report it!
