### ISSUE TITLE
Fix Docker builds

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#169]
@assignUser These builds were intermittently failing for a while, so i wasn't too worried, but now they seem to be systematically failing. Like at https://github.com/ropensci-review-tools/pkgcheck/actions/runs/4364383671. I can't immediately see what's wrong, except maybe a general need to update some of the components. You able to offer any insights / help? :+1: 

---

Edit: It fails on `docker/build-push-action@v2`, but that action [is now up to v4](https://github.com/docker/build-push-action). I don't really know what the differences are? It's likely fine to just upgrade version there, but I'll wait to see whether you know more.

**Comment by assignUser** [comment]
Updating the action version doesn't hurt but the problem here is a stale apt index:
```
2 Err:2 https://r2u.stat.illinois.edu/ubuntu focal/main all r-cran-bspm all 0.4.2-1.ca2004.1
#6 2.152   404  Not Found [IP: 192.17.190.167 443]
#6 2.733 Fetched 514 kB in 1s (625 kB/s)
```
I'll open a PR,
