### ISSUE TITLE
pkgcheck misses GitHub workflows CI checks

### ISSUE THREAD

**Issue by caropradier** [ropensci-review-tools/pkgcheck#179]
Running locally pkgcheck() for [eph](https://github.com/holatam/eph) seems to miss the checks implemented at https://github.com/holatam/eph/tree/master/.github/workflows

This issue seems similar to closed issue #87 

Thanks for your help!

**Comment by mpadge** [comment]
Seems to be all okay, with workflow clearly [succeeding](https://github.com/holatam/eph/actions/runs/5382226669), checks [dumped into issue](https://github.com/holatam/eph/issues/48), and package now [submitted for review](https://github.com/ropensci/software-review/issues/593). With that, I'll close this and wish you all the best with the review. Feel free to ask any further questions you might have.
