### ISSUE TITLE
goodpractice archived on CRAN

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#198]
Thanks to @jromanowska via https://github.com/ropensci/software-review/issues/637#issuecomment-2084667554. See also #20, which describes what has to be done. goodpractice issue is https://github.com/MangoTheCat/goodpractice/issues/163

**Comment by assignUser** [comment]
Hm, again? :/

**Comment by mpadge** [comment]
@assignUser Interestingly, the Docker build wasn't yet failing, because `r2u` still indexed and successfully installed the CRAN version of goodpractice. The above commit just switches to a GitHub install, which will continue to work no matter what.
