### ISSUE TITLE
Dump goodpractice, run each part separately

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#20]
Mostly because the `covr` component is run with hard-coded default arguments, and so gets coverage from `tests` directory only. This should be estimated from full package, including vignettes and examples, so needs to be run separately. This would also allow an initial [`pkgbuild`](https://github.com/r-lib/pkgbuild) check to ensure package can be successfully built and loaded prior to proceeding with anything else.

**Comment by assignUser** [comment]
This would possibly also allow to change the output of the parts to include :heavy_multiplication_x:  on important bits, which would make the github action fail.

**Comment by mpadge** [comment]
In current form, any errors on any parts of `goodpractice` will lead to :heavy_multiplication_x: in `summary.pkgcheck()`, and so to an action fail. Or did you mean something else?

**Comment by assignUser** [comment]
That's what I mean, nice!

**Comment by mpadge** [comment]
Maintainance of `goodpractice` has finally be taken over again by somebody else, so this issue can be closed for now, hoping resopnsibility for things like this will be taken up in the future by the new maintainers.
