### ISSUE TITLE
Vignette links to Packaging Guide are broken

### ISSUE THREAD

**Issue by willgearty** [ropensci-review-tools/pkgcheck#207]
I'm currently going through the list of checks that are run in [this vignette](https://docs.ropensci.org/pkgcheck/articles/list-checks.html), and I noticed most of the links out to the Packaging Guide are broken and redirect to the tops of the pages instead of the specific headings (e.g., https://devguide.ropensci.org/building.html#licence).

**Comment by mpadge** [comment]
Thanks so much for catching that @willgearty. You'll see you now also appear of the [front page list of *allcontributors*](https://github.com/ropensci-review-tools/pkgcheck?tab=readme-ov-file#issue-authors). I appreciate your attention to detail!
