### ISSUE TITLE
pkgcheck() run error

### ISSUE THREAD

**Issue by piyalkarum** [ropensci-review-tools/pkgcheck#23]
I have pkgcheck installed on R 4.0.0 and I get the following error upon running pkgcheck(), for any package for that matter.

Error in readr::read_tsv(f, col_names = cnames, col_types = ctypes, col_select = cnames,  : 
  unused arguments (col_select = cnames, lazy = FALSE)

**Comment by mpadge** [comment]
Need a reprex with URL of package being checked please. Also include version info of `readr`, because the error is related to recent update to `readr` v0. 2. Or just update that package and see if that fixes. Thanks!

**Comment by piyalkarum** [comment]
SOLVED
Thanks for the prompt reply. It was the latest version from github that I installed I believe 0.0.1.367. Reinstalling readr package solved the problem.

**Comment by mpadge** [comment]
Great, thanks!
