### ISSUE TITLE
Add documentation in summary tables

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#28]
Maybe a link to docs somewhere?

Or something on hover, but I'd assume it needs more checks of accessibility for screenreader users.

**Comment by mpadge** [comment]
Image from @maelle to contextualise this:

![image (1)](https://user-images.githubusercontent.com/6697851/132003597-d032d955-3b8f-4441-9a29-d4573e686594.png)

The `"measure"` column needs explaining and interpreting

**Comment by mpadge** [comment]
The solution which will be committed presently comes from [this gist](https://gist.github.com/SteveLane/1794eaa9791b4687e8cd#tooltips-for-html-output-in-rmarkdown-documents) - much simpler and more flexible than [`tippy`](https://github.com/JohnCoene/tippy).
