### ISSUE TITLE
What new checks are welcome

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#36]
This is a question related to the new vignette. Should the intro clarify when a new check should be added?

And if you have a fork, you'd need to make sure it's in sync, there's no way to store more checks outside the package, correct?

**Comment by mpadge** [comment]
Yes, clarifying what sort of new checks are welcome is a good idea. As for storing more checks - that will come once the package becomes more aligned with [`riskmetric`](https://github.com/pharmar/riskmetric). That package allows that by simply assuming any functions in the global namespace with specified prefixes define checks. I'll try to address this soon. Thanks!

**Comment by mpadge** [comment]
The broader point about integrating local checks moved to #40
