### ISSUE TITLE
do not use .Platform$file.sep

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#41]
Replace `strsplit` calls with this as separator with the [`decompose_path()` function from `pkgstats`](https://github.com/ropensci-review-tools/pkgstats/blob/f6affd8ad5a75fa02abd2f80ddf28ae10d8561f1/R/utils.R#L20-L24). This is probably what is causing current Windows failures.

**Comment by maelle** [comment]
Aaah I came here after looking at that CI failure once more time.

Why not take a dependency on fs?

**Comment by mpadge** [comment]
Only because I was asking @jeroen for his failsafe way of deconstructing windows paths, for which he suggested `fs`, and that made me realise the one required thing from that package is simply the link above to:
``` r
   strsplit (f, "^(?=/)(?!//)|(?<!^)(?<!^/)/", perl = TRUE)
```
I just have to put that in this package too, and it should be fixed.
