### ISSUE TITLE
rm COC

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#42]
in favor of rOpenSci COC (does this org need a .github repo?)

**Comment by maelle** [comment]
it'd be nice to create https://github.com/ropensci-review-tools/.github (as a copy of https://github.com/ropensci/.github) so GitHub can link to the COC from e.g. issues.

**Comment by mpadge** [comment]
Hey, that's really cool how that automatically just works like that - thanks!!

**Comment by maelle** [comment]
what doesn't work is the inclusion of the COC in the pkgdown sidebar as the COC isn't in the repo, but that's fine for rOpenSci packages since the footer is the same as the main website and mentions the COC.
