### ISSUE TITLE
Clarify "add new" comment

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#50]
In 10 new checks, will there be 10 checks between "add new" and the "end" comment? Or should new checks/summaries be added _right before_ such a comment?

**Comment by mpadge** [comment]
All very much a work-in-progress, particularly subject to discussions in #40, which will determine the form than both new and local tests can and should actually take, and the way that both new and local tests are/may be integrated into the package. I expect a lot more clarify by the end of the week. In the meantime, could you please clarify whether you're referring to [adding them to the return object](https://github.com/ropensci-review-tools/pkgcheck/blob/e084f822b1725480fcecc81ce60d24dadf124d28/R/pkgcheck-fn.R#L33-L37) or to the [markdown conversion function](https://github.com/ropensci-review-tools/pkgcheck/blob/e084f822b1725480fcecc81ce60d24dadf124d28/R/format-checks.R#L65-L71), or something else?

**Comment by maelle** [comment]
Both! I do not understand why new checks have to be added between two markers. After a while, there will be a dozen checks between the two markers?

**Comment by mpadge** [comment]
Ah, i see. I just thought it might be helpful to indicate, but yeah, i see your point. Maybe those markers should just be removed, and the suggestion changes to one that tests should be added at a context-appropriate place within both of those files? Feel free to modify anything accordingly :rocket:
