### ISSUE TITLE
Add period at the end of items in Markdown

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#55]
I can't find it but I think I once saw something about this being more accessible?

**Comment by maelle** [comment]
I can only find https://developers.google.com/style/lists#numbered-lettered-bulleted-lists but there's no explanation.

**Comment by mpadge** [comment]
It's all from [Strunk & White](https://en.wikipedia.org/wiki/The_Elements_of_Style) which really ought to be adhered to at all times. But in what specific context did you mean that here?

**Comment by maelle** [comment]
e.g. `- :heavy_check_mark: Package uses 'roxygen2'`

**Comment by mpadge** [comment]
Looks good both ways, but maybe even better with terminal period?

![pkgcheck](https://user-images.githubusercontent.com/6697851/133113326-215744b5-0977-46c8-bc92-e2d81ea1901d.png)

**Comment by maelle** [comment]
yes better with terminal period indeed :-)
