### ISSUE TITLE
why the option and not an env var

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#60]
Here: https://github.com/ropensci-review-tools/pkgcheck/blob/cdedd4e1c5190d7bfca7e498ab0856d884e30b7f/R/checks-goodpractice.R#L13

**Comment by mpadge** [comment]
Options are inherited by `processx`, envvars aren't. That whole `processx`/`callr` system works exclusively via options. Makes no difference here, but `roreviewapi` needs these to be options in order to correctly access these values. Please close if that is clear :+1:
