### ISSUE TITLE
Regex on 'All applicable standards' has changed

### ISSUE THREAD

**Issue by christophsax** [ropensci-review-tools/pkgcheck#63]
The message from srr has changed:

> All applicable standards [v0.0.1] have been documented in this package

But the regex here has not. Instead of:

https://github.com/ropensci-review-tools/pkgcheck/blob/34cf3e719d5b92b82c079866c53ca6bcb8ed89e6/R/checks-srr.R#L33

There should now be something like this:

```r
    if (!methods::is (srr, "error") &
        any (grepl ("^All applicable standards \\[.+\\] have been documented in this package", srr))) {
        srr_okay <- TRUE
    }
```

**Comment by mpadge** [comment]
Thanks @christophsax - please feel free to directly PR any more things like this you find. That one fell through the gaps because I don't yet have any test packages which meet that criterion, so only ever test the fail message :wink:
