### ISSUE TITLE
Default value for path?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#65]
It'd be nice if the default value for path were either the active usethis project or the current directory.

**Comment by mpadge** [comment]
Thanks @maelle, that's obviously an important thing to add. Done by adding one more no-imports dep of `rprojroot`, and implementing the relevant bits of [`usethis::proj_path()`](https://github.com/r-lib/usethis/blob/master/R/proj.R).

**Comment by maelle** [comment]
Awesome, thank you! Idea gotten by wrongly assuming that was already the behavior :grin:

**Comment by mpadge** [comment]
Nah, just one of those things i hadn't got around to, and most likely was always going to wait for a nudge exactly like yours :laughing: . Thanks!
