### ISSUE TITLE
what do the current test files test?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#66]
E.g. what is bg?

**Comment by maelle** [comment]
I can guess but I wonder whether it should be more explicit.

**Comment by mpadge** [comment]
Getting there, but iteratively. Started with `pkgstats` today, which went from 2 to 5 test files, and increased coverage by > 25%. Expanding and properly structuring these tests is next is line. Thanks for the incentive!

**Comment by maelle** [comment]
Even to start small, the message in

https://github.com/ropensci-review-tools/pkgcheck/blob/754a79b50287be9db8bc7e01dc3275498a3f85c6/tests/testthat/test-bg.R#L1

can only get more explicit :grin:
