### ISSUE TITLE
Make the RoxygenNote removal a test helper i.e. a  function?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#67]

**Comment by mpadge** [comment]
Could you explain a bit more? In what context would that be used/applied? Just internally here, or more generally?

**Comment by maelle** [comment]
just to remove duplication + make tests more readable (it adds quite a bit of clutter for a newcomer to the file at least in my opinion) here

https://github.com/ropensci-review-tools/pkgcheck/blob/754a79b50287be9db8bc7e01dc3275498a3f85c6/tests/testthat/test-bg.R#L14

and

https://github.com/ropensci-review-tools/pkgcheck/blob/754a79b50287be9db8bc7e01dc3275498a3f85c6/tests/testthat/test-pkgcheck.R#L10

**Comment by mpadge** [comment]
Those lines have now been removed, so closing here.
