### ISSUE TITLE
why no print for output_pkgchk_has_citation()?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#83]
https://docs.ropensci.org/pkgcheck/articles/extending-checks.html#the-output-function

**Comment by mpadge** [comment]
No real reason; just keeping the final print stuff initially minimal. Do you think it would help to print the citation as part of the full output? Note especially that anything printed there will also appear on the package checks of every issue. Most checks are just that, and are only intended to populate the `summary` method which forms the initial checklist at the top of the printed output. `print` methods are mostly for where that contains additional necessary information. I'm not sure the details of a citation are really necessary?

**Comment by maelle** [comment]
Then could you add this comment in the vignette? Right after that example there's "This object must be a list with the following three items" which makes the example look non complete.

**Comment by mpadge** [comment]
Yes, I'll definitely do that

**Comment by maelle** [comment]
@mpadge in the vignette I'd like the rationale on _why/when_ to suppress a print method to be more explicit.

**Comment by mpadge** [comment]
@maelle I think this is actually addressed in a hopefully satisfactory manner in the latest version, but it's not yet being built by the doc server - docs there are 4 days old or so; will hopefully soon be fixed and rebuilt.

**Comment by maelle** [comment]
Ok. Leaving this unread to read next week + at last submit a check for dependendencies.
