### ISSUE TITLE
Could the output_pkgchk_ functions only get the check results?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#84]
They could be found by name / something else.

It feels a bit cumbersome to get the whole checks?

**Comment by mpadge** [comment]
Yes, but ... (quoting from elsewhere in this context ...):

> that would also require splitting the main object into two objects, one as input (everything but checks), and one as output (the checks). That division would be artificial, and they'd have to be stitched back together somewhere anyway. But more importantly: The current design intentionally allows a check to also insert additional checks$info if that needs to be pulled in from elsewhere. That's not done at present, but is possible. If checks can't see checks (which would be good in principle), they also couldn't be expected to modify info, and that would reduce extensibility in that context.

I'll address the other current issues (#80, #83) first, then come back to this

**Comment by mpadge** [comment]
Closing this issue to continue discussion in #81
