### ISSUE TITLE
pkgcheck misses GitHub actions CI checks

### ISSUE THREAD

**Issue by noamross** [ropensci-review-tools/pkgcheck#87]
In https://github.com/ropensci/software-review/issues/470#issuecomment-937980756 , we seem to miss the checks implemented at https://github.com/ewallace/tidyqpcr/actions

**Comment by maelle** [comment]
Or clearer instructions in dev guide + more informative failure message in pkgcheck.

**Comment by maelle** [comment]
Perfect, thanks. I'm actually leaning towards not encouraging badges more than present. (My opinion might change based on e.g. https://github.com/r-lib/pkgdown/issues/1299)
