### ISSUE TITLE
Do not install ctags in the vignette if it's already there

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#90]
https://github.com/ropensci-review-tools/pkgcheck/blob/27036396ec317b544205ca03c5f35359c08692dc/vignettes/extending-checks.Rmd#L29

**Comment by mpadge** [comment]
Wow, you're quick! It should be all okay, and is there as a direct copy of [`stantargets`](https://github.com/ropensci/stantargets/blob/9a0132e9ff2496ac4f35c507d89c84be29933f3b/vignettes/simulation.Rmd#L28-L30), as suggested by Jeroen. The `ctags_install()` function does nothing if either (1) both are already installed, or (2) it's not a unix system. It's there solely for the rOpenSci doc server, which needs it's own independent installation. All okay then?

**Comment by maelle** [comment]
aaah ok!! can you add this in a comment in the vignette?

I didn't check it took time, I was actually hindered by my having an older pkgstats version locally without the function at all. :sweat_smile:

**Comment by mpadge** [comment]
It's related to [this issue](https://github.com/r-lib/styler/issues/460), for which [the fix](https://github.com/r-lib/styler/pull/462) was fairly simple but only gets switched on if `is_plain_r_file`, which a `.Rmd` vignette is not. I'll ping him over there
